name: vagabond
description: An offline map app for hiking.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase: ^0.0.1-dev.16
  flutter_map: ^0.12.0
  latlong2: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_map:
    git:
      url: git@github.com:fleaflet/flutter_map.git
      ref: issues/829-nullsafety

flutter:
  uses-material-design: true
  assets:
    - .env
